[package]
name = "gpg-ed25519-to-cv25519"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dryoc = "0.4"
sequoia-openpgp = "1.10"
nettle = "7.2"
